from .batch import BatchError, BatchResult
from .client import FLClient
from .config import (
    CircuitBreakerConfig,
    ClientConfig,
    ProxyConfig,
    RateLimitConfig,
    RetryConfig,
    TimeoutConfig,
)
from .easy import (
    Client,
    Pages,
    fetch_freelancers,
    fetch_project,
    fetch_projects,
    fetch_user,
)
from .exceptions import (
    AuthenticationRequired,
    BlockedError,
    CircuitOpenError,
    ConfigurationError,
    EmptyPageError,
    FLRUError,
    HTTPStatusError,
    ParseError,
    RateLimitedError,
    RobotsDeniedError,
    SecurityError,
    SelectorDriftError,
    TransportError,
    UnexpectedPageError,
)
from .filters import ProjectFilters, ProjectType
from .models import (
    Attachment,
    Category,
    CrawlCheckpoint,
    FreelancerPage,
    FreelancerSummary,
    Image,
    Link,
    Money,
    PageData,
    ParseDiagnostics,
    PortfolioItem,
    ProjectDetail,
    ProjectKind,
    ProjectPage,
    ProjectRecord,
    ProjectStatus,
    ProjectSummary,
    RequestMetrics,
    Review,
    SourceInfo,
    UserProfile,
    UserSummary,
)
from .observability import RequestEvent, StructuredLogHandler
from .state import (
    CrawlStateStore,
    MemoryStateStore,
    PostgresStateStore,
    RedisStateStore,
    SQLiteStateStore,
    project_content_hash,
)

__version__ = "0.3.2"

AsyncClient = Client

__all__ = [
    "__version__",
    "AsyncClient",
    "Attachment",
    "AuthenticationRequired",
    "BatchError",
    "BatchResult",
    "BlockedError",
    "Category",
    "CircuitBreakerConfig",
    "CircuitOpenError",
    "Client",
    "ClientConfig",
    "ConfigurationError",
    "CrawlCheckpoint",
    "CrawlStateStore",
    "EmptyPageError",
    "FLClient",
    "FLRUError",
    "FreelancerPage",
    "FreelancerSummary",
    "HTTPStatusError",
    "Image",
    "Link",
    "MemoryStateStore",
    "Money",
    "PageData",
    "Pages",
    "ParseDiagnostics",
    "ParseError",
    "PortfolioItem",
    "PostgresStateStore",
    "ProjectDetail",
    "ProjectFilters",
    "ProjectKind",
    "ProjectPage",
    "ProjectRecord",
    "ProjectStatus",
    "ProjectSummary",
    "ProjectType",
    "ProxyConfig",
    "RateLimitConfig",
    "RateLimitedError",
    "RedisStateStore",
    "RequestEvent",
    "RequestMetrics",
    "RetryConfig",
    "Review",
    "RobotsDeniedError",
    "SQLiteStateStore",
    "SecurityError",
    "SelectorDriftError",
    "SourceInfo",
    "StructuredLogHandler",
    "TimeoutConfig",
    "TransportError",
    "UnexpectedPageError",
    "UserProfile",
    "UserSummary",
    "project_content_hash",
    "fetch_freelancers",
    "fetch_project",
    "fetch_projects",
    "fetch_user",
]
